### ISSUE TITLE
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found

### ISSUE THREAD

**Issue by coolmansr** [emx0r/PT_PHELPER#4]
Hello,

Running from raspberry pi in test mode before crontab:

pi@binance-btc:~/profittrailer $ pico pairs_helper.sh 
pi@binance-btc:~/profittrailer $ ./pairs_helper.sh BINANCE 15 0 0
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found
./pairs_helper.sh: 1: ./pairs_helper.sh: bc: not found

Obviously nothing in pairs.properties:
#PT_PHELPER@MK
# Sat 24 Feb 10:43:36 CET 2018

Cheers,

**Comment by emx0r** [comment]
Hi,

can you please check if you have bc command in your system?
Location should be standard executable path: /usr/bin/bc

if you don't have it, then depending on your OS, please try to install like: apt-get install bc

**Comment by pottertech** [comment]
Yes I do but that is because I had already realized it was missing and installed it.

But thanks for looking out!

**Comment by emx0r** [comment]
seems I overlooked it, I was thinking it's part of Raspbian. I'll update doc.

**Comment by pottertech** [comment]
You can make one more modification that will help build telegram-cli

Change:

sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython-dev make 

To:

sudo apt-get install libreadline-dev libconfig-dev libssl1.0-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython-dev make 

Ensuring that libssl1.0-dev is used instead of libssl-dev.

**Comment by emx0r** [comment]
Thanks for the hint will update it. 
Also I'll make pt_phelper.sh as the main script to be used.
I've been testing i with few people for some time and it looks like it behaves well

**Comment by emx0r** [comment]
fixed by installing bc, doc updated
